### ISSUE TITLE
Fails to install on node 12 macos

### ISSUE THREAD

**Issue by dennismphil** [Alorel/shrink-ray#41]
# Description

Fails to `npm install shrink-ray-current` on Mac OS on 

```
$ node -v                 
v12.12.0
```

with the following error
```
CXX(target) Release/obj.target/iltorb/src/dec/stream_decode.o
../src/dec/stream_decode.cc:14:72: error: no matching member function for call to 'ToObject'
    Local<Object> dictionary = Nan::Get(params, key).ToLocalChecked()->ToObject();
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/Users/**/Library/Caches/node-gyp/12.12.0/include/node/v8.h:2576:44: note: candidate function not viable: requires single argument 'context', but no arguments were
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/**/Library/Caches/node-gyp/12.12.0/include/node/v8.h:2590:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were
      provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../src/dec/stream_decode.cc:40:49: error: no matching member function for call to 'ToObject'
  StreamDecode* obj = new StreamDecode(info[0]->ToObject());
                                       ~~~~~~~~~^~~~~~~~
/Users/**/Library/Caches/node-gyp/12.12.0/include/node/v8.h:2576:44: note: candidate function not viable: requires single argument 'context', but no arguments were
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/**/Library/Caches/node-gyp/12.12.0/include/node/v8.h:2590:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were
      provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../src/dec/stream_decode.cc:48:35: error: no matching member function for call to 'ToObject'
  Local<Object> buffer = info[0]->ToObject();
                         ~~~~~~~~~^~~~~~~~
/Users/**/Library/Caches/node-gyp/12.12.0/include/node/v8.h:2576:44: note: candidate function not viable: requires single argument 'context', but no arguments were
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/**/Library/Caches/node-gyp/12.12.0/include/node/v8.h:2590:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were
      provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../src/dec/stream_decode.cc:54:16: error: no matching member function for call to 'BooleanValue'
  if (info[2]->BooleanValue()) {
      ~~~~~~~~~^~~~~~~~~~~~
/Users/**/Library/Caches/node-gyp/12.12.0/include/node/v8.h:2603:8: note: candidate function not viable: requires single argument 'isolate', but no arguments were
      provided
  bool BooleanValue(Isolate* isolate) const;
       ^
/Users/**/Library/Caches/node-gyp/12.12.0/include/node/v8.h:2606:51: note: candidate function not viable: requires single argument 'context', but no arguments were
      provided
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
../src/dec/stream_decode.cc:70:16: error: no matching member function for call to 'BooleanValue'
  if (info[1]->BooleanValue()) {
      ~~~~~~~~~^~~~~~~~~~~~
/Users/**/Library/Caches/node-gyp/12.12.0/include/node/v8.h:2603:8: note: candidate function not viable: requires single argument 'isolate', but no arguments were
      provided
  bool BooleanValue(Isolate* isolate) const;
       ^
/Users/**/Library/Caches/node-gyp/12.12.0/include/node/v8.h:2606:51: note: candidate function not viable: requires single argument 'context', but no arguments were
      provided
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
5 errors generated.
make: *** [Release/obj.target/iltorb/src/dec/stream_decode.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/**/**/workspace/einstein-platform-console/node_modules/iltorb
gyp ERR! node -v v12.12.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN shrink-ray-current@4.1.2 requires a peer of iltorb@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN shrink-ray-current@4.1.2 requires a peer of node-zopfli-es@^1.0.3 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iltorb@1.3.10 install: `detect-libc prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iltorb@1.3.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/**/.npm/_logs/2019-10-14T20_04_48_306Z-debug.log
```

The installation succeeds on Node 10 and Node 11. However, fails on 12

**Comment by Alorel** [comment]
The installation [works fine](https://travis-ci.org/Alorel/shrink-ray/jobs/599051836) on osx & node 12. Are your build tools up to date?

Additionally, the error comes from the iltorb module, not shrink-ray-current.

**Comment by dennismphil** [comment]
The error stopped showing up now. Thanks for checking.

![bitmoji](https://render.bitstrips.com/v2/cpanel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-27f3d64a-b3a3-43b8-a269-f9caa01ea0d8-v1.png?transparent=1&palette=1&width=246)
